# Generated by Django 5.1.7 on 2025-04-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=100),
        ),
    ]
